---
output:
  reprex::reprex_document:
    venue: "gh"
    advertise: FALSE
    session_info: TRUE
    style: TRUE
    comment: "#;-)"
    tidyverse_quiet: FALSE
    std_out_err: TRUE
knit: reprex::reprex_render
---
<<<<<<< Updated upstream
=======

setwd("C:/Users/mcpro/OneDrive/Documents/WAVE LAB/Code/shadows_3afc/tools")

>>>>>>> Stashed changes
## Quiet tidyverse

The tidyverse meta-package is quite chatty at startup, which can be very useful in exploratory, interactive work. It is often less useful in a reprex, so by default, we suppress this.

However, when `tidyverse_quiet` is `FALSE`, the rendered result will include a tidyverse startup message about package versions and function masking.

```{r, eval = requireNamespace("tidyverse", quietly = TRUE)}
library(tidyverse)
```



```{r}
table <- read.csv("data/dataframe_answer.csv", header = TRUE)
```

```{r}
table <- table |> mutate(chosen_object = str_remove_all(chosen_image,"^obj|_sha.*"))

table <- table |> mutate(consistent_object = chosen_object == target_object)
table <- table |> mutate(consistent_shadow = chosen_object == target_shadow)
table <- table |> mutate(all_object = consistent_object & consistent_shadow)
table <- table |> mutate(neither = (chosen_object != target_object) & (chosen_object != target_shadow))
```


```{r}
table |>
  mutate(Category = case_when(
    all_object ~ "Both",
    consistent_object & !all_object ~ "Object Only",
    consistent_shadow & !all_object ~ "Shadow Only"
  )) |>
  filter(!is.na(Category)) |>
  count(Category) |>
  mutate(
    percent = n / sum(n),
    # This calculates the midpoint of each slice for label placement
    label_pos = cumsum(n) - (0.5 * n)) |>
  ggplot(aes(x = "", y = n, fill = Category)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y", start = 0) + # This turns the bar into a pie
  geom_text(aes(y = label_pos, 
                label = scales::percent(percent, accuracy = 1)), 
            size = 5, 
            color = "white") +
  labs(title = "Object Memory Responses") +
  theme_void()
```


```{r}
table |>
  pivot_longer(
    cols = c(consistent_object, consistent_shadow, all_object, neither), 
    names_to = "Category", 
    values_to = "Status"
  ) |>
  filter(Status == TRUE) |>
  ggplot(aes(x = Category, fill = Category)) +
  geom_bar() +
  scale_x_discrete(labels = c(
    "neither" = "Neither",
    "all_object" = "Both",
    "consistent_object" = "Object",
    "consistent_shadow" = "Shadow"
  )) + 
  scale_fill_discrete(
    labels = c("neither" = "Neither",
    "all_object" = "Both",
    "consistent_object" = "Object",
    "consistent_shadow" = "Shadow")
  ) +
  labs(
    title = "Object Memory Responses",
    y = "Count"
  ) +
  theme(plot.title = element_text(hjust = 0.5))
```



```{r}
sum(table$consistent_object)
sum(table$consistent_shadow)
sum(table$all_object)
sum(table$neither)
```



```{r}

ggplot(table, aes(x = as.factor(calced_stim_duration_rounded), fill = as.factor(calced_stim_duration_rounded))) +
  geom_bar() +
  labs(
    title = "Count of Records per Category",
    x = "Category",
    y = "Number of Records",
    fill = "Category"
  ) +
  theme_minimal()
  
  
  
  
  
```  




```{r}
table |>
  filter(calced_stim_duration_rounded == 500) |>
  pivot_longer(
    cols = c(consistent_object, consistent_shadow, all_object, neither), 
    names_to = "Category", 
    values_to = "Status"
  ) |>
  filter(Status == TRUE) |>
  ggplot(aes(x = Category, fill = Category)) +
  geom_bar() +
  scale_x_discrete(labels = c(
    "neither" = "Neither",
    "all_object" = "Both",
    "consistent_object" = "Object",
    "consistent_shadow" = "Shadow"
  )) + 
  scale_fill_discrete(
    labels = c("neither" = "Neither",
    "all_object" = "Both",
    "consistent_object" = "Object",
    "consistent_shadow" = "Shadow")
  ) +
  labs(
    title = "Responses When Stim = 500ms",
    y = "Count"
  ) +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
table |>
  filter(calced_stim_duration_rounded == 700) |>
  pivot_longer(
    cols = c(consistent_object, consistent_shadow, all_object, neither), 
    names_to = "Category", 
    values_to = "Status"
  ) |>
  filter(Status == TRUE) |>
  ggplot(aes(x = Category, fill = Category)) +
  geom_bar() +
  scale_x_discrete(labels = c(
    "neither" = "Neither",
    "all_object" = "Both",
    "consistent_object" = "Object",
    "consistent_shadow" = "Shadow"
  )) + 
  scale_fill_discrete(
    labels = c("neither" = "Neither",
    "all_object" = "Both",
    "consistent_object" = "Object",
    "consistent_shadow" = "Shadow")
  ) +
  labs(
    title = "Responses When Stim = 700ms",
    y = "Count"
  ) +
  theme(plot.title = element_text(hjust = 0.5))
```
```{r}
table |>
  filter(calced_stim_duration_rounded != 500 & calced_stim_duration_rounded != 700) |>
  pivot_longer(
    cols = c(consistent_object, consistent_shadow, all_object, neither), 
    names_to = "Category", 
    values_to = "Status"
  ) |>
  filter(Status == TRUE) |>
  ggplot(aes(x = Category, fill = Category)) +
  geom_bar() +
  scale_x_discrete(labels = c(
    "neither" = "Neither",
    "all_object" = "Both",
    "consistent_object" = "Object",
    "consistent_shadow" = "Shadow"
  )) + 
  scale_fill_discrete(
    labels = c("neither" = "Neither",
    "all_object" = "Both",
    "consistent_object" = "Object",
    "consistent_shadow" = "Shadow")
  ) +
  labs(
    title = "Responses When Stim = 900ms",
    y = "Count"
  ) +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
table |>
  pivot_longer( #join columns
    cols = c(consistent_object, consistent_shadow, all_object, neither), 
    names_to = "Response_Type", 
    values_to = "Status"
  ) |>  
  filter(Status == TRUE) |> #count true values
  #merge with as factor logic for timing
  ggplot(aes(x = as.factor(calced_stim_duration_rounded), fill = Response_Type)) +
  geom_bar(position = "stack") + 
  scale_fill_discrete(
    labels = c(
      "neither" = "Neither",
      "all_object" = "Both",
      "consistent_object" = "Object",
      "consistent_shadow" = "Shadow"
    )
  ) +
  labs(
    title = "Responses by Stimulus Duration",
    x = "Duration (ms)",
    y = "Count",
    fill = "Category"
  ) +
  theme_minimal()

```


```{r}
table |>
filter()  



```
